"""Add account_label to connected_accounts

Revision ID: 7ee6f1407d02
Revises: ed1d04ba3a82
Create Date: 2026-03-04 12:27:07.337378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee6f1407d02'
down_revision = 'ed1d04ba3a82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('account_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_accounts', 'account_label')
    # ### end Alembic commands ###
