"""add source column to events

Revision ID: b766999cc5e5
Revises: f1a2b3c4d5e6
Create Date: 2026-04-25 19:43:35.506975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b766999cc5e5'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('events', sa.Column('external_event_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'external_event_id')
    op.drop_column('events', 'source')
    # ### end Alembic commands ###
