"""Add source and external_event_id to events

Revision ID: f1a2b3c4d5e6
Revises: 7ee6f1407d02
Create Date: 2026-04-11 12:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1a2b3c4d5e6"
down_revision = "7ee6f1407d02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("source", sa.String(50), server_default="manual", nullable=False),
    )
    op.add_column(
        "events", sa.Column("external_event_id", sa.String(255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "external_event_id")
    op.drop_column("events", "source")
    # ### end Alembic commands ###
